FROM maven:3.9.6-eclipse-temurin-21-alpine as builder

COPY producer-service/src /usr/app/src
COPY producer-service/pom.xml /usr/app
COPY pom.xml /usr/

RUN mvn -f /usr/app/pom.xml clean package

FROM eclipse-temurin:21-alpine

COPY --from=builder /usr/app/target/*.jar /usr/app/app.jar

ENTRYPOINT ["java", "-jar", "/usr/app/app.jar"]